---
# tasks file for perfsonar-toolkit

- name: Make sure we can use htpasswd module
  package:
    name: python-passlib
    state: latest
  when: perfsonar_web_passwd is not none
  tags: [ 'ps::install' ]

- name: Add the credentials to log in the perfSONAR web admin GUI
  htpasswd:
    path: /etc/perfsonar/toolkit/psadmin.htpasswd
    name: "{{ perfsonar_web_user }}"
    password: "{{ perfsonar_web_passwd }}"
    state: present
  when: perfsonar_web_passwd is not none
  tags: [ 'ps::config' ]

# TODO: check the webadmin is reachable and login works

