---
# tasks file for perfsonar-toolkit

- name: Need python-passlib or python3-passlib  based on python version Ansible uses. Needed to work with htpasswd module
  tags: [ 'ps::config' ]
  package:
    name: "{{ passlibpkg}}"
    state: latest

- name: Add the credentials to log in the perfSONAR web admin GUI
  tags: [ 'ps::config' ]
  htpasswd:
    path: /etc/perfsonar/toolkit/psadmin.htpasswd
    name: "{{ perfsonar_web_user }}"
    password: "{{ perfsonar_web_passwd }}"
    state: present
  when: perfsonar_web_passwd is not none

# TODO: check the webadmin is reachable and login works

