---
# tasks file for perfsonar-toolkit

- name: Need python-passlib to work with htpasswd module
  tags: [ 'ps::config' ]
  package:
    name: python-passlib
    state: latest
  when: ansible_distribution is "CentOS" and ansible_distribution_major_version is "7"

- name: Need python3-passlib to work with htpasswd module
  tags: [ 'ps::config' ]
  package:
    name: python3-passlib
    state: latest
  when: ansible_distribution is not "CentOS" or ansible_distribution_major_version is not "7"

- name: Add the credentials to log in the perfSONAR web admin GUI
  tags: [ 'ps::config' ]
  htpasswd:
    path: /etc/perfsonar/toolkit/psadmin.htpasswd
    name: "{{ perfsonar_web_user }}"
    password: "{{ perfsonar_web_passwd }}"
    state: present
  when: perfsonar_web_passwd is not none

# TODO: check the webadmin is reachable and login works

